apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: prod
spec:
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: website
          image: ghcr.io/flotio-dev/website-next:3.0
          env:
            - name: NEXT_PUBLIC_API_URL
              value: https://api.flotio.ovh
            - name: NEXT_PUBLIC_APP_URL
              value: https://app.flotio.ovh
          resources:
            limits:
              memory: "256Mi"
              cpu: "1000m"
            requests:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
