---
all:
  vars:
    ansible_user: ansible
    ansible_python_interpreter: /usr/bin/python3
  children:
    control_plane:
      hosts:
        vm1:
          ansible_host: 192.168.1.10
    workers:
      hosts:
        vm2:
          ansible_host: 192.168.1.11
        vm3:
          ansible_host: 192.168.1.12
