apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
