apiVersion: v1
kind: Service
metadata:
  name: redis-dev
  namespace: dev
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: redis
