apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-dev
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
