apiVersion: v1
kind: Service
metadata:
  name: db-dev
  namespace: dev
  labels:
    app: db-dev
spec:
  type: LoadBalancer
  selector:
    app: db-dev
  ports:
    - name: db-dev
      port: 5432
      targetPort: 5432