apiVersion: v1
kind: Secret
metadata:
  name: postgres-admin
  namespace: dev
type: Opaque
stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-cbackend
  namespace: dev
type: Opaque
stringData:
  CBACKEND_USER: "flotio"
  CBACKEND_PASSWORD: "flotio"
  