apiVersion: batch/v1
kind: Job
metadata:
  name: pg-provision-cbackend
  namespace: prod
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        job: pg-provision-cbackend
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: POSTGRES_USER
          command:
            [
              "sh",
              "-c",
              "until pg_isready -h postgres-prod -p 5432 -U $POSTGRES_USER; do echo 'waiting for postgres...'; sleep 30; done",
            ]
      containers:
        - name: create-user-and-db
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: POSTGRES_PASSWORD
            - name: CBACKEND_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-cbackend
                  key: CBACKEND_USER
            - name: CBACKEND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-cbackend
                  key: CBACKEND_PASSWORD
          command: ["sh", "-c"]
          args:
            - |
              set -e

                  # Create user if missing
                  psql -v ON_ERROR_STOP=1 -h db-dev -U "$POSTGRES_USER" -d postgres <<SQL
              DO \$do\$
              BEGIN
                IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${CBACKEND_USER}') THEN
                  EXECUTE format('CREATE ROLE %I WITH LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE', '${CBACKEND_USER}', '${CBACKEND_PASSWORD}');
                END IF;
              END
              \$do\$;
              SQL

                  # Create DB if missing
                  psql -h db-dev -U "$POSTGRES_USER" -d postgres <<SQL
              SELECT format('CREATE DATABASE %I OWNER %I', '${CBACKEND_USER}', '${CBACKEND_USER}')
              WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname='${CBACKEND_USER}')
              \gexec
              SQL

                  # Grant privileges
                  psql -h postgres-prod -U "$POSTGRES_USER" -d postgres -c "GRANT ALL PRIVILEGES ON DATABASE ${CBACKEND_USER} TO ${CBACKEND_USER};"
