apiVersion: v1
kind: Service
metadata:
  name: postgres-prod
  namespace: prod
  labels:
    app: postgres-prod
spec:
  type: ClusterIP
  selector:
    app: postgres-prod
  ports:
    - name: postgres-prod
      port: 5432
      targetPort: 5432
