---
- name: Install Ingress Nginx
  ansible.builtin.command: kubectl apply -f {{ ingress_nginx_manifest_url }}
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: ingress_nginx_install
  changed_when: "'created' in ingress_nginx_install.stdout or 'configured' in ingress_nginx_install.stdout"
  when: ingress_nginx_enabled

- name: Wait for Ingress Nginx controller
  ansible.builtin.command: kubectl -n {{ ingress_nginx_namespace }} rollout status deployment/ingress-nginx-controller --timeout={{ ingress_nginx_wait_timeout }}
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: false
  when: ingress_nginx_enabled
