apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: dev
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "REPLACE_ME",
          "password": "REPLACE_ME",
          "email": "REPLACE_ME"
        }
      }
    }
