apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-api
  namespace: dev
spec:
  selector:
    matchLabels:
      app: core-api
  template:
    metadata:
      labels:
        app: core-api
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
      - name: core-api
        image: ghcr.io/flotio-dev/core-api:0.4
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"
          requests:
            memory: "128Mi"
            cpu: "500m"          
        ports:
        - containerPort: 8080
