apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: dev
spec:
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
      - name: website
        image: ghcr.io/flotio-dev/website:11.5
        env:
        - name: NEXT_PUBLIC_API_BASE_URL
          value: http://api-svc:8080
        - name: NEXT_PUBLIC_GITHUB_APP
          value: flotio-app
        - name: NEXTAUTH_URL
          value: https://flotio.ovh
        - name: NEXTAUTH_SECRET
          value: nextauth-dev-secret-456
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"
          requests:
            memory: "128Mi"
            cpu: "500m"          
        ports:
        - containerPort: 3000
