apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ovh-credentials-reader
  namespace: cert-manager
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["ovh-credentials"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ovh-credentials-reader-binding
  namespace: cert-manager
subjects:
- kind: ServiceAccount
  name: cert-manager-webhook-ovh
  namespace: default
roleRef:
  kind: Role
  name: ovh-credentials-reader
  apiGroup: rbac.authorization.k8s.io
  