apiVersion: v1
kind: Secret
metadata:
  name: pve-exporter
  namespace: monitoring
type: Opaque
stringData:
  pve.yml: |
    default:
      user: "root@pam!monitoring"
      token_name: "monitoring"
      token_value: "REPLACE_WITH_PROXMOX_TOKEN_VALUE"
      verify_ssl: false

